/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package adminpassword;

import java.security.SecureRandom;

/**
 *
 * @author Exelsion
 */
public class Generator extends javax.swing.JFrame {

    /**
     * Creates new form Generator
     */
    public Generator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        longitudCb = new javax.swing.JComboBox<>();
        simbolosCheck = new javax.swing.JCheckBox();
        numerosCheck = new javax.swing.JCheckBox();
        minusculasCheck = new javax.swing.JCheckBox();
        mayusculasCheck = new javax.swing.JCheckBox();
        passField = new javax.swing.JTextField();
        generarButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 253, 215));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 253, 215));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Generador de Password Seguro", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Existence Light", 0, 14))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Existence Light", 0, 18)); // NOI18N
        jLabel2.setText("Longitud");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 41, -1, -1));

        jLabel4.setFont(new java.awt.Font("Existence Light", 0, 18)); // NOI18N
        jLabel4.setText("Incluir Simbolos");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 69, -1, -1));

        jLabel5.setFont(new java.awt.Font("Existence Light", 0, 18)); // NOI18N
        jLabel5.setText("Incluir numeros");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 97, -1, -1));

        jLabel6.setFont(new java.awt.Font("Existence Light", 0, 18)); // NOI18N
        jLabel6.setText("Incluir minusculas");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 125, -1, -1));

        jLabel7.setFont(new java.awt.Font("Existence Light", 0, 18)); // NOI18N
        jLabel7.setText("Incluir mayusculas");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 153, -1, -1));

        longitudCb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "8", "16", "32", "64", "128", "256", "512", "1024", " " }));
        jPanel2.add(longitudCb, new org.netbeans.lib.awtextra.AbsoluteConstraints(284, 43, -1, -1));

        simbolosCheck.setBackground(new java.awt.Color(255, 253, 215));
        simbolosCheck.setSelected(true);
        simbolosCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simbolosCheckActionPerformed(evt);
            }
        });
        jPanel2.add(simbolosCheck, new org.netbeans.lib.awtextra.AbsoluteConstraints(284, 69, -1, -1));

        numerosCheck.setBackground(new java.awt.Color(255, 253, 215));
        numerosCheck.setSelected(true);
        jPanel2.add(numerosCheck, new org.netbeans.lib.awtextra.AbsoluteConstraints(284, 97, -1, -1));

        minusculasCheck.setBackground(new java.awt.Color(255, 253, 215));
        minusculasCheck.setSelected(true);
        jPanel2.add(minusculasCheck, new org.netbeans.lib.awtextra.AbsoluteConstraints(284, 125, -1, -1));

        mayusculasCheck.setBackground(new java.awt.Color(255, 253, 215));
        mayusculasCheck.setSelected(true);
        jPanel2.add(mayusculasCheck, new org.netbeans.lib.awtextra.AbsoluteConstraints(284, 153, -1, -1));

        passField.setToolTipText("");
        jPanel2.add(passField, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 591, 34));

        generarButton.setBackground(new java.awt.Color(208, 109, 127));
        generarButton.setFont(new java.awt.Font("Glamourgirl", 0, 24)); // NOI18N
        generarButton.setForeground(new java.awt.Color(72, 55, 71));
        generarButton.setText("Generar");
        generarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generarButtonActionPerformed(evt);
            }
        });
        jPanel2.add(generarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 202, 214, 62));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 253, 215));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void simbolosCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simbolosCheckActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_simbolosCheckActionPerformed

    private void generarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generarButtonActionPerformed
        // TODO add your handling code here:
        String charafull = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789~`!@#$%^&*()-_=+[{]}\\\\|;:\\'\\\",<.>/?";
        String upperC = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";
        String lowerC = "abcdefghijklmnopqrstuvwxyz";
        String numbers = "0123456789";
        String specialCh = "~`!@#$%^&*()-_=+[{]}\\\\|;:\\'\\\",<.>/?";
        StringBuilder sb = new StringBuilder();
        SecureRandom rnd = new SecureRandom();
        String finalPw; 
        
        String noUpper = charafull.replace(upperC, "");
        String noLower = charafull.replace(lowerC, "");
        String noNumber = charafull.replace(numbers, "");
        String noSpecialCh = charafull.replace(specialCh, "");
        String nolowerUpper = charafull.replace(upperC + lowerC, "");
        
        String sum = "";
    
        //int passLength = (int)longitudCb.getSelectedItem();
        String passSs = longitudCb.getSelectedItem().toString();
        int passLength = Integer.parseInt(passSs);
        
        if(simbolosCheck.isSelected()){
            sum= sum.concat(specialCh);
        }
        if(numerosCheck.isSelected()){
            sum = sum.concat(numbers);
        }
        if(mayusculasCheck.isSelected()){
            sum = sum.concat(upperC);
        }
        if(minusculasCheck.isSelected()){
            sum = sum.concat(lowerC);
        }
        for(int i = 0; i<passLength ; i++){
            sb.append(sum.charAt(rnd.nextInt(sum.length()))); 
        }
        /*
        if (simbolosCheck.isSelected() && numerosCheck.isSelected() && minusculasCheck.isSelected() && mayusculasCheck.isSelected()){
           for(int i = 0; i<passLength ; i++){
            sb.append(noUpper.charAt(rnd.nextInt(noUpper.length())));            
           }
        }
        */
        finalPw = sb.toString();
        passField.setText(finalPw);
        //passField.setText(passSs);
       
    }//GEN-LAST:event_generarButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Generator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Generator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Generator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Generator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Generator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton generarButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JComboBox<String> longitudCb;
    private javax.swing.JCheckBox mayusculasCheck;
    private javax.swing.JCheckBox minusculasCheck;
    private javax.swing.JCheckBox numerosCheck;
    private javax.swing.JTextField passField;
    private javax.swing.JCheckBox simbolosCheck;
    // End of variables declaration//GEN-END:variables
}
